version: '3.8'

services:
  config-service:
    image: sihyogeon/homeless-cde-msa:config-service
    container_name: app-config-service-1
    ports:
      - "8888:8888"
    networks:
      - msa-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  discovery-service:
    image: sihyogeon/homeless-cde-msa:discovery-service
    container_name: app-discovery-service-1
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - "8761:8761"
    networks:
      - msa-network
    restart: always

  gateway-service:
    image: sihyogeon/homeless-cde-msa:gateway-service
    container_name: app-gateway-service-1
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - "8181:8181"
    networks:
      - msa-network
    restart: always

  user-service:
    image: sihyogeon/homeless-cde-msa:user-service
    container_name: app-user-service-1
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - msa-network
    restart: always

  friends-service:
    image: sihyogeon/homeless-cde-msa:friends-service
    container_name: app-friends-service-1
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - msa-network
    restart: always

  server-service:
    image: sihyogeon/homeless-cde-msa:server-service
    container_name: app-server-service-1
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - msa-network
    restart: always

  chat-service:
    image: sihyogeon/homeless-cde-msa:chat-service
    container_name: app-chat-service-1
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - msa-network
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - msa-network
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - msa-network
    restart: always

volumes:
  redis_data:

networks:
  msa-network:
    driver: bridge
