services:
  user-service:
    image: sihyogeon/homeless-cde-msa:user-service
    networks:
      - msa-network

  friends-service:
    image: sihyogeon/homeless-cde-msa:friends-service
    networks:
      - msa-network

  server-service:
    image: sihyogeon/homeless-cde-msa:server-service
    networks:
      - msa-network

  chat-service:
    image: sihyogeon/homeless-cde-msa:chat-service
    networks:
      - msa-network

  discovery-service:
    image: sihyogeon/homeless-cde-msa:discovery-service
    ports:
      - "8761:8761"
    networks:
      - msa-network

  gateway-service:
    image: sihyogeon/homeless-cde-msa:gateway-service
    ports:
      - "8181:8181"
    networks:
      - msa-network


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - msa-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - msa-network

volumes:
  redis_data:
  mysql_data:

networks:
  msa-network:
    driver: bridge
