server:
  port: 8888

spring:
  #  profiles:         # ?? ?? ??, ????? ?? ???? ???????.
  #    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:homeless-code-team/homeless-code_config.git
          default-label: main
          username: bildno
          password: ${GIT_PRIVATE_KEY}




