server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file://C:/Users/gingu/Desktop/develop/homeless-code-config

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, health, beans


