server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
        git:
          uri: https://github.com/homeless-code-team/homeless-code-config.git
          private-key: file:///C:\Users\playdata\.ssh

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, health, beans


