server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: file://C:/home/homeless-code-config
        git:
          uri: file://C:/home/homeless-code-config

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, health, beans


