server:
  port: 8181

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]": # 모든 경로에 대한 CORS 설정
            allowed-origins:
              - "http://homelesscode.shop" # 허용할 클라이언트 도메인
              - "https://homelesscode.shop" # 허용할 클라이언트 도메인
              - "http://localhost:3000"
              # - 나중에 도메인
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowed-headers:
              - "Content-Type"
              - "Authorization"
              - "X-Requested-With"
              - "Accept"
              - "Origin"
              - "Access-Control-Request-Method"
              - "Access-Control-Request-Headers"
            exposed-headers:
              - "Authorization"
              - "Set-Cookie"
              - "Content-Type"
            allow-credentials: true # 쿠키 및 인증 정보 허용
            max-age: 3600 # Preflight 요청 캐싱 시간 (초)

      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: homeless-code Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
        - name: DedupeResponseHeader
          args:
            name: Access-Control-Allow-Credentials Access-Control-Allow-Origin
            strategy: RETAIN_FIRST
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: friends-service
          uri: lb://FRIENDS-SERVICE
          predicates:
            - Path=/friends-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/friends-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

            # 채팅 서비스(웹소켓) STOMP인터셉터가 토큰 검증함.
        - id: chat-service-ws
          predicates:
            - Path=/chat-service/ws/**, /ws/**
          uri: lb://CHAT-SERVICE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}



        - id: server-service
          uri: lb://SERVER-SERVICE
          predicates:
            - Path=/server/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter

        - id: server-service
          uri: lb://server-service
          predicates:
            - Path=/server/actuator
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/server-service/(?<segment>.*), /$\{segment}
            #- AuthorizationHeaderFilter

jwt:
  secretKey: rI9KLc/nWq+0ehvbQXjST52lIHi+A4PurdKwAe0ZcN+0LE1QBv7p0qhFx8wzt8PaigtMXpJHdIl6p4ILsLDasA==

security:
  excluded-paths:
    - /api/v1/users/sign-up
    - /api/v1/users/confirm
    - /api/v1/users/sign-in
    - /api/v1/users/duplicate
    - /api/v1/users/refresh-token
    - /api/v1/users/swagger-ui/**
    - /api/v1/users/swagger-ui.html
    - /api/v1/friends/swagger-ui/**
    - /api/v1/friends/swagger-ui/html
    - /api/v1/users/callback
    - /ws/info
    - /ws/**
    - /oauth2/authorization/**
    - /login/oauth2/code/**
    - /oauth2/**
    - /oauth2/authorization/**
    - /api/v1/oauth2/authorization/**

# log level setting
