server:

  port: 8181
spring:
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,PATCH"
      allowed-headers: "*"
      exposed-headers: "Authorization"
      allow-credentials: true
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/homeless-user?serverTimezone=Asia/Seoul
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      host: localhost  # Redis ?? ??
      port: 6379       # Redis ?? ??
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: homelesscode.noreply@gmail.com
    password: cpgh cvxh fsiq yifi
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


security:
  excluded-paths:
    - /api/v1/users/sign-up
    - /api/v1/users/confirm
    - /api/v1/users/sign-in
    - /api/v1/users/duplicate
    - /api/v1/users/refresh-token


instance:
  instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
#cloud:
#  aws:
#    s3:
#      bucket: homeless-bucket
#    credentials:
#      access-key:
#      secret-key:
#    region:
#      static:
jwt:
  exclude-paths:
    - /api/v1/users/sign-up
    - /api/v1/users/confirm
    - /api/v1/users/sign-in
    - /api/v1/users/duplicate
    - /api/v1/users/refresh-token
  expiration: 3600000
  secretKey: rI9KLc/nWq+0ehvbQXjST52lIHi+A4PurdKwAe0ZcN+0LE1QBv7p0qhFx8wzt8PaigtMXpJHdIl6p4ILsLDasA==
  expirationRt: 1209600000
  secretKeyRt: lGBm6kwqJoKjLioZfyYJ+OTstjyczTbf7tJXar1pQ2PDSeg5LZQ30DXDlLbM7zKiysBfPkdv6KTVOJ+UcL5C6g==
logging:
  level:
    org.springframework.security : DEBUG