server:
  port: 0
spring:
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
      exposed-headers: "Authorization"
      allow-credentials: true
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/homeless-user?serverTimezone=Asia/Seoul
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      host: localhost  # Redis ?? ??
      port: 6379       # Redis ?? ??
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          debug: true # ??? ??? (?? ?? ? ?? ???)

security:
  excluded-paths:
    - /user/signup
    - /user/confirm
    - /user/signin
    - /user/duplicate/*

instance:
  instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
