server:
  port: 0
spring:
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
      exposed-headers: "Authorization"
      allow-credentials: true
  application:
    name: user-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: homelesscode.noreply@gmail.com
    password: cpgh cvxh fsiq yifi
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


security:
  excluded-paths:
    - /api/v1/users/sign-up
    - /api/v1/users/confirm
    - /user-service/api/v1/users/sign-in
    - /api/v1/users/sign-in
    - /api/v1/users/duplicate

instance:
  instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
