server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/사용자이름/설정저장소.git
          username: {GITHUB_USERNAME}  # Jenkins에서 주입
          password: {GITHUB_TOKEN}     # Jenkins에서 주입
          default-label: develop

management:
  endpoints:
    web:
      exposure:
        include: health, beans
