server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/homeless-code-team/homeless-code-config.git
          username: si-cpu
          password: ${GIT_ACCESSTOKEN}
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: health, beans

logging:
  level:
    org.springframework.cloud.config: debug
