server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/homeless-code-team/homeless-code-config.git
          username: si-cpu
          password: ${GITHUB_TOKEN}  # 여기서 GitHub Token을 환경 변수로 설정
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, health, beans


